---
- hosts: hajpdemo

  remote_user: eyindan

  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u40-b26/jdk-8u40-linux-x64.rpm
    download_folder: /tmp
    java_name: "{{download_folder}}/jdk1.8.0_40"
    java_archive: "{{download_folder}}/jdk-8u40-linux-x64.rpm"

  tasks:
  - name: Check if foo.rpm is installed
    command: rpm -q jdk1.8.0_40-1.8.0_40-fcs.x86_64
    register: rpm_check
    ignore_errors: True

  - name: Install wget package (RedHat based)
    action: yum name='wget' state=installed
    sudo: yes
    when: rpm_check.rc == 1

  - name: Download Java
    command: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{java_archive}}"
    when: rpm_check.rc == 1

  - name: Install rpm
    command: "rpm -Uvh {{java_archive}}"
    ignore_errors: yes
    sudo: yes
    when: rpm_check.rc == 1

  - name: Make Java available for system
    command: 'alternatives --install "/usr/bin/java" "java" "/usr/java/latest/bin/java" 2000'
    sudo: yes
    when: rpm_check.rc == 1

  - name: Clean up
    file: state=absent path={{java_archive}}
    when: rpm_check.rc == 1
